import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtempSync, readFileSync, realpathSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { stringify } from 'yaml';
import { compileConfigurationFile } from '../src/runtime/configuration-file.js';
import { fixture } from './runtime-fixture.js';

test('file authoring agrees across formats and rejects executable inputs, symlinks, invalid encoding and oversized files', t => {
  const root = realpathSync(mkdtempSync(join(tmpdir(), 'runtime-config-file-')));
  const owner = randomUUID();
  writeFileSync(join(root, '.owner'), owner, { flag: 'wx' });
  t.after(() => { assert.equal(readFileSync(join(root, '.owner'), 'utf8'), owner); rmSync(root, { recursive: true }); });
  const json = join(root, 'input.json');
  const yaml = join(root, 'input.yaml');
  writeFileSync(json, JSON.stringify(fixture()));
  writeFileSync(yaml, stringify(fixture()));
  assert.deepEqual(compileConfigurationFile(json), compileConfigurationFile(yaml));
  const source = join(root, 'builder.ts');
  writeFileSync(source, 'throw Error("This must never execute")');
  assert.throws(() => compileConfigurationFile(source), /FILE_FORMAT/);
  const link = join(root, 'link.json');
  symlinkSync(json, link);
  assert.throws(() => compileConfigurationFile(link));
  writeFileSync(json, Buffer.from([0xc3, 0x28]));
  assert.throws(() => compileConfigurationFile(json), /UTF8/);
  writeFileSync(json, Buffer.alloc(1048577, 32));
  assert.throws(() => compileConfigurationFile(json), /FILE_SIZE/);
});
